name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: setup
      id: setup
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: setup
        setup-command: python3 -m venv venv; venv/bin/python -m pip install flake8 pep8-naming flake8-docstrings numpy pytest
        command: "venv/bin/python -m pip install -e ."
        timeout: 1
        max-score: 0
    - name: exercise-4-3
      id: exercise-4-3
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: exercise-4-3
        setup-command: ''
        command: "venv/bin/python -m flake8 life/"
        timeout: 1
        max-score: 1
    - name: exercise-4-4-1
      id: exercise-4-4-1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: exercise-4-4-1
        setup-command: ''
        command: "venv/bin/python -m pytest tests/test_exercise_4_4_1.py"
        timeout: 1
        max-score: 1
    - name: exercise-4-4-2
      id: exercise-4-4-2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: exercise-4-4-2
        setup-command: ''
        command: "venv/bin/python -m pytest tests/test_exercise_4_4_2.py"
        timeout: 1
        max-score: 1
    - name: exercise-4-4-3
      id: exercise-4-4-3
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: exercise-4-4-3
        setup-command: ''
        command: "venv/bin/python -m pytest tests/test_exercise_4_4_3.py"
        timeout: 1
        max-score: 1
    - name: exercise-4-5
      id: exercise-4-5
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: exercise-4-5
        setup-command: ''
        command: "venv/bin/python -m pytest tests/test_exercise_4_5.py"
        timeout: 1
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        EXERCISE-4-3_RESULTS: "${{steps.exercise-4-3.outputs.result}}"
        EXERCISE-4-4-1_RESULTS: "${{steps.exercise-4-4-1.outputs.result}}"
        EXERCISE-4-4-2_RESULTS: "${{steps.exercise-4-4-2.outputs.result}}"
        EXERCISE-4-4-3_RESULTS: "${{steps.exercise-4-4-3.outputs.result}}"
        EXERCISE-4-5_RESULTS: "${{steps.exercise-4-5.outputs.result}}"
      with:
        runners: exercise-4-3, exercise-4-4-1, exercise-4-4-2,
          exercise-4-4-3, exercise-4-5